### ISSUE TITLE
Set shards according to growth from previous days

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/chronos#4]
When creating shards for new indices we need to reflect on the growth of the last x days in terms of number of documents

**Comment by seiflotfy** [comment]
We should use http://borischumichev.github.io/everpolate/

**Comment by martinpinto** [comment]
In order to set the shards according to the growth from previous days we must have a historisation of the growth rate from previous days. With this historisation we can apply a linear regression to predict all future growth rates.

**Comment by seiflotfy** [comment]
Its all there, if you query the state of the last indices in ES
